language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t navinsourie/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true navinsourie/react-test npm test

after_success:
  - docker build -t navinsourie/multi-client ./client
  - docker build -t navinsourie/multi-nginx ./nginx
  - docker build -t navinsourie/multi-server ./server
  - docker build -t navinsourie/mult-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push navinsourie/multi-client
  - docker push navinsourie/multi-nginx
  - docker push navinsourie/multi-server
  - docker push navinsourie/multi-worker
